version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-cli-template-export"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-chkrp61wj2om"
s3_prefix = "sam-cli-template-export"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"shop-http-api\" StageName=\"prod\""
image_repositories = []
